/**
 * Word pool for the reading drills. Common English words of mixed length, so
 * recognition is the work rather than vocabulary.
 */
export const WORDS = [
  'about', 'above', 'across', 'after', 'again', 'against', 'almost', 'alone',
  'along', 'already', 'always', 'among', 'answer', 'around', 'because', 'become',
  'before', 'begin', 'behind', 'believe', 'below', 'between', 'beyond', 'bring',
  'build', 'carry', 'catch', 'centre', 'change', 'child', 'choose', 'clear',
  'close', 'colour', 'common', 'correct', 'country', 'course', 'cover', 'cross',
  'decide', 'deep', 'depend', 'differ', 'divide', 'during', 'early', 'earth',
  'effort', 'either', 'enough', 'enter', 'equal', 'every', 'example', 'expect',
  'family', 'father', 'field', 'figure', 'finish', 'first', 'follow', 'force',
  'forest', 'forget', 'fresh', 'front', 'future', 'garden', 'gather', 'general',
  'govern', 'green', 'group', 'grow', 'happen', 'heavy', 'history', 'hold',
  'house', 'human', 'hundred', 'idea', 'important', 'include', 'increase', 'inside',
  'island', 'keep', 'language', 'large', 'later', 'learn', 'leave', 'lecture',
  'letter', 'level', 'light', 'listen', 'little', 'machine', 'market', 'matter',
  'measure', 'member', 'middle', 'might', 'minute', 'moment', 'money', 'month',
  'morning', 'mother', 'mountain', 'moved', 'music', 'nature', 'never', 'night',
  'north', 'nothing', 'notice', 'number', 'object', 'ocean', 'offer', 'office',
  'often', 'order', 'other', 'paper', 'parent', 'party', 'people', 'perhaps',
  'period', 'person', 'picture', 'piece', 'place', 'plant', 'point', 'power',
  'present', 'press', 'price', 'problem', 'produce', 'promise', 'public', 'quick',
  'quiet', 'radio', 'reach', 'ready', 'reason', 'record', 'remain', 'remember',
  'report', 'result', 'return', 'river', 'round', 'school', 'science', 'season',
  'second', 'section', 'seem', 'sense', 'series', 'serve', 'settle', 'several',
  'short', 'should', 'shoulder', 'simple', 'since', 'single', 'sister', 'small',
  'social', 'sound', 'south', 'space', 'speak', 'special', 'spend', 'spring',
  'square', 'stand', 'start', 'state', 'still', 'stone', 'story', 'street',
  'strong', 'student', 'study', 'subject', 'sudden', 'summer', 'suppose', 'surface',
  'system', 'table', 'teach', 'thank', 'their', 'there', 'thing', 'think',
  'third', 'those', 'though', 'thought', 'through', 'today', 'together', 'toward',
  'travel', 'truth', 'under', 'until', 'usual', 'value', 'village', 'visit',
  'voice', 'waste', 'watch', 'water', 'weather', 'weight', 'were', 'where',
  'whether', 'which', 'while', 'white', 'whole', 'whose', 'window', 'winter',
  'within', 'without', 'woman', 'wonder', 'word', 'world', 'worry', 'would',
  'write', 'wrong', 'yesterday', 'young',
].filter((w) => /^[a-z]+$/.test(w))
